### ISSUE TITLE
Support for directive mapping

### ISSUE THREAD

**Issue by wtrocki** [IBM/openapi-to-graphql#235]
Hello

I'm working on complex API definitions that contain many endpoints and object definitions. 
I was curious if it is possible to map some metadata in open api to graphql directives. 

Swagger has extensions functionality that can be used here:
https://swagger.io/specification/#specificationExtensions

## How this could work

Simply having extensions containing the directive will be very useful for cater to advanced use cases where json build in Open API will be also represented as GraphQL Schema.

```yaml
 x-graphql-directive:
    name: hasRole
    values:
      - name: roleName
        value: john@doe.com
```

I would love to contribute that change to Openapi-to-graphql
