### ISSUE TITLE
Invalid runtime expression in link parameters for nested json in response body

### ISSUE THREAD

**Issue by shuchengit** [IBM/openapi-to-graphql#257]
Hi,
I keep getting an invalid runtime expression when trying to link 2 of my restful api together. The special case here is that the first api will return a json that is nested, such as:

```
{
  "key": "p1",
  "name": "Parent1",
  "child": {
    "key": "c1"
  }
}
```

And in the response links of this api we define the parameters as:

```
          links:
            child:
              operationId: getChild
              parameters:
                key: '$response.body#/child/key'
```
I have read the runtime expression part of the spec over and over again and I believe it confirms to the example given there for the /user/uuid usecase. Could anyone please give me some pointer of why this is not working?

The error I am getting when trying to get the child attributes from GraphQL is:
      "message": "Cannot create link because '$response.body#/child/key' is an invalid runtime expression"
