### ISSUE TITLE
Cannot generate schema from Box OpenAPI Spec

### ISSUE THREAD

**Issue by carlgrimm** [IBM/openapi-to-graphql#310]
Attempting to convert from https://raw.githubusercontent.com/box/box-openapi/en/openapi.json

Validation of the OAS has been performed and passes using Spectral. The oas-validation package seems to be hanging up over a default of null in the specification at #/paths/~1tasks/post/requestBody/content/application~1json/properties/due_at (note that schema should come after /applications~1json/ which is strange)

due_at contains a default: null value which when changed to default: "" keeps the oas-validation error from occurring. However, the error "OpenAPI-to-GraphQL creation event error:  Cannot read property 'schema' of undefined" persists.

I didn't note any debug flags I could set. Any guidance on how to track this error down?

**Comment by arminrosu** [comment]
Had a quick look at this, some observations:

1. conversion fails at on point because during `schema_builder.createFields()` because the `Tags` `fieldTypeDefinition` does not have a `subDefinition`. There are multiple properties missing a `subDefinition`.

2. The tags property of `File` is defined as:

```yml
tags:
  allOf:
    - type: array
      example:
        - approved
      items:
        type: string
      minItems: 1
      maxItems: 100
      description: ...
    - x-box-field-variant: 2
    - nullable: false
```

Removing `allOf` and declaring the properties on `tags` does not generate an error.

3. The OAS is massive, 918kB in JSON. Can you break it down and isolate the offending parts? Would make debugging easier.
