### ISSUE TITLE
Currently unsupported HTTP authentication protocol type 'http' and scheme 'bearer' in OAS

### ISSUE THREAD

**Issue by AnirudhaGohokar** [IBM/openapi-to-graphql#322]
Am not able to generate schema from openapi 3.0.1 spec when using bearer scheme. Getting below error

`Error: UNSUPPORTED_HTTP_SECURITY_SCHEME - Currently unsupported HTTP authentication protocol type 'http' and scheme 'bearer' in OAS`

I have my security scheme defined as below:

```
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

Is there any alternative way to fix this?

**Comment by AnirudhaGohokar** [comment]
Finally got it running. Did following changes:

Change security scheme type to `apiKey`

```
securitySchemes:
    bearerAuth:
      type: apiKey
      in: header
      name: Authorization
```

Create oas options object

```
let oasOptions = {
            strict:true,
        headers: {
            'X-Origin': 'GraphQL'
        },
        tokenJSONpath: '$.jwt'
    };

```

Pass object as a param:

`const { schema, report } = await createGraphQLSchema(usersSwagger,oasOptions);`

Add middleware to append jwt in request:
```
router.use(function (req, res, next) {
        // put the jwt back into the request so oasgraph can use it for
        // the context of each request via the tokenJSONPath option
        if (req.headers && req.headers.authorization) {
            req.jwt = req.headers.authorization.replace(/^Bearer /, '');
            console.log('----------->>',req.jwt);
        }
        next();
    });
```
