### ISSUE TITLE
Enums: keep original value option

### ISSUE THREAD

**Issue by PseudoSky** [IBM/openapi-to-graphql#357]
**Describe the bug**
There isn't a way to keep the literal enum values from the oas spec.
The external api may require the enum to be exactly the same as what is defined.
Regardless of the options the values always seem to be sanitized to uppercase + underscore.

**Proposal**

- Map the enum values to valid values
- Store the mapping in state somehow
- Reverse the mapping of the values before the request is made

**OR**

I think it would be much more useful to add a fetch override option to the configuration -
so the consumer can implement more complex solutions / fix assumptions made by the library

- More easily map custom resolvers
- Add delegated resolvers
- Linking is currently near impossible with message envelopes
- Many more

No idea how complicated this would be within the library, I'm trying to avoid attempting it
Looking for thoughts on this

**To Reproduce**
Example
```yaml
TextFilter:
      description: Text filter
      required:
        - key
        - operator
        - value
      properties:
        key:
          type: string
          description: Key on an object
          enum:
            - id
            - name
            - assetType
        operator:
          type: string
          enum:
            - Equals
            - Does not equal
            - Contains
            - Does not contain
```

**Expected behavior**

I need the value posted to the external api to be "Does not equal" rather than "DOES_NOT_EQUAL"
